### ISSUE TITLE
Issue in loading masonry 4.2.2 with jquery 3.6 and angularjs 1.8.2

### ISSUE THREAD

**Issue by taruna896** [desandro/masonry#1166]
Getting error in loading angularjs pages with masonry 4.2.2 library.
TypeError: $(...).masonry is not a function

Using angularjs 1.8.2 and jquery 3.6 versions with masonry.
It works fine with 3.1.5 version of masonry and jquery 3.6 versions
